### ISSUE TITLE
Missing Documentation. 

### ISSUE THREAD

**Issue by itsayushch** [Allvaa/lava-spotify#4]
Hi there, the documentation for this library is not mentioned. It would be great if you could write one. 
Thank you.

**Comment by Allvaa** [comment]
hi, thanks for your suggestion but i actually made this package just for my [music bot](https://github.com/Allvaa/lavalink-musicbot). so there are no docs. i guess you were brought here from npmjs and i have noticed that someone published my package without permission

**Comment by Allvaa** [comment]
well, I was planning to publish the package in the future if it's ready but someone published it before me without my permission :/
